[package]
name = "beeline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"
benimator = "2.0"
impacted = { version = "1.3", features = ["bevy-06"] }
rand = "0.8"
